name: Go CI Pipeline

on:
  push:
    branches:
      - "**"
      - staging
      - main
  pull_request:
    branches:
      - "**"
      - staging
      - main

env:
  GO_VERSION: "1.22"

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Linter
        run: echo "Skipping lint for now"

      - name: Run Tests
        run: go test ./... -v -coverprofile=coverage.out

      - name: Build
        run: go build -v ./...

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out